### PR TITLE
feature: support issues-only analysis and log upload parsing failures CY-5727

### PR DESCRIPTION
**Pull request by pedrocodacy**
Adds capability to run only issues analysis.

I was already possible for duplication and metrics, just extending it to fit the use case of some customers (and to mitigate our limitation of payload size for duplication and metrics)

### CODE REVIEW

**Comment by pedrocodacy** [comment]
added a log for the contents of the response when it fails, we should be able to see more details that way

I left the delay function implemented for us to test if it patches the problem, for now I left no delay being applied.

**Comment by pedrocodacy** [comment]
added a log for the contents of the response when it fails, we should be able to see more details that way

I left the delay function implemented for us to test if it patches the problem, for now I left no delay being applied.

**Comment by pedrocodacy** [comment]
added a log for the contents of the response when it fails, we should be able to see more details that way

I left the delay function implemented for us to test if it patches the problem, for now I left no delay being applied.

**Review by vascorsd — APPROVED** [review]

**Review by machadoit — APPROVED** [review]
LGTM!

**Pull request merged**
